### ISSUE TITLE
can not play with vlc

### ISSUE THREAD

**Issue by dddd64693** [4gray/iptvnator#333] opened 2023-12-06 05:19 UTC
it can't be player with vlc player 
path of vlc:D:\Program Files\VideoLAN\VLC\vlc.exe
version:the latest  v0.15.0
![image](https://github.com/4gray/iptvnator/assets/14047878/ea5dd7cf-8a8f-4bf9-8a11-acb43af4dfda)

![image](https://github.com/4gray/iptvnator/assets/14047878/d6917d30-4cf1-4a68-87b7-eb6ad8d55818)

**Comment by omeringen** [comment] 2023-12-06 08:23
https://github.com/4gray/iptvnator/issues/315

**Comment by omeringen** [comment] 2023-12-08 06:21
> > #315
> 
> it's not work

yep. Your report is a duplicate of #315

**Comment by 4gray** [comment] 2024-01-02 18:50
duplicate of #315

**Closed** 2024-01-02 18:51 UTC

**Comment by skaox** [comment] 2024-03-04 06:20
Hello,
I found a way to use vlc on windows just have to install it to :
C:\VideoLAN\VLC\

In iptvnator (settings) put for mpv AND vlc path :
C:\VideoLAN\VLC\vlc.exe

Then vlc should launch. No ?

I'm using it with xtreme/xtream code,
nothing to report for Live Streams and VOD Streams but
Series are not working same thing with linux and windows.

Instead of the information message,
The video is playing in external player window

I have this :

![iptvnator_series_not_launching_with_vlc](https://github.com/4gray/iptvnator/assets/22966700/39765e2a-0997-4042-821d-4ff0c516c283)

Synopsis font color in black is not readable.
Hope there will be an update soon.
Thank you

**Comment by ioptu** [comment] 2024-11-01 03:32
delete the vlc player path you have added in app settings then  save&quit .

edit config.json in  %appdata%/iptvnator 

"VLC_PLAYER_PATH": "D:\\Program Files\\VideoLAN\\VLC\\vlc.exe"

save file then launch the app .
