### ISSUE TITLE
Embed external media players into IPTVnator frame

### ISSUE THREAD

**Issue by nt74** [4gray/iptvnator#472] opened 2024-11-28 12:22 UTC
**Can external media players VLC and MPV become embedded in the same frame as IPTVnator?**
Maybe this is an old topic or suggestion but I wanted to bring it up anyways. 
Is it maybe possible to embed external media players like VLC and MPV into the IPTVnator frame?
I meant in the same way as the native HTML5 and Java players are. Having such a solution might even attract more potential interested users out there.

**Comment by glennlunder** [comment] 2024-12-17 06:32
This request is kindof a dupe of #443

**Comment by 4gray** [comment] 2024-12-19 20:06
yep, see #433

**Closed by 4gray** 2024-12-19 20:06 UTC
